#pragma once

#include "Control/adenv.h"
#include "Control/adsr.h"
#include "Control/line.h"
#include "Control/phasor.h"

#include "Drums/analogbassdrum.h"
#include "Drums/analogsnaredrum.h"
#include "Drums/hihat.h"
#include "Drums/synthbassdrum.h"
#include "Drums/synthsnaredrum.h"

#include "Dynamics/balance.h"
#include "Dynamics/compressor.h"
#include "Dynamics/crossfade.h"
#include "Dynamics/limiter.h"

#include "DaisySP/Effects/autowah.h"
#include "Effects/bitcrush.h"
#include "Effects/chorus.h"
#include "Effects/decimator.h"
#include "Effects/flanger.h"
#include "Effects/fold.h"
#include "Effects/overdrive.h"
#include "Effects/phaser.h"
#include "Effects/pitchshifter.h"
#include "Effects/reverbsc.h"
#include "Effects/sampleratereducer.h"
#include "Effects/tremolo.h"

#include "Filters/allpass.h"
#include "Filters/atone.h"
#include "Filters/biquad.h"
#include "Filters/comb.h"
#include "Filters/fir.h"
#include "Filters/mode.h"
#include "Filters/moogladder.h"
#include "Filters/nlfilt.h"
#include "Filters/svf.h"
#include "Filters/tone.h"

#include "Noise/clockednoise.h"
#include "Noise/dust.h"
#include "Noise/fractal_noise.h"
#include "Noise/grainlet.h"
#include "Noise/particle.h"
#include "Noise/whitenoise.h"

#include "PhysicalModeling/KarplusString.h"
#include "PhysicalModeling/PolyPluck.h"
#include "PhysicalModeling/drip.h"
#include "PhysicalModeling/modalvoice.h"
#include "PhysicalModeling/pluck.h"
#include "PhysicalModeling/resonator.h"
#include "PhysicalModeling/stringvoice.h"

#include "Synthesis/blosc.h"
#include "Synthesis/fm2.h"
#include "Synthesis/formantosc.h"
#include "Synthesis/harmonic_osc.h"
#include "Synthesis/oscillator.h"
#include "Synthesis/oscillatorbank.h"
#include "Synthesis/variablesawosc.h"
#include "Synthesis/variableshapeosc.h"
#include "Synthesis/vosim.h"
#include "Synthesis/zoscillator.h"
